### ISSUE TITLE
compatibility to SUPEE-8167

### ISSUE THREAD

**Issue by arosenhagen** [aligent/Magento-Paypalfixes#9]
*New Patch for PayPal Instant Payment Notification (IPN) Changes.
Upgrade to 1.9.3.3 or SUPEE-8167 by June 30, 2017 to Avoid Service Disruptions*

> As of June 30, 2017, PayPal Instant Payment Notifications will no longer allow you to use HTTP to post messages back to PayPal for verification. To comply with these changes, all merchants using PayPal must upgrade to Community Edition 1.9.3.3 or apply the SUPEE-8167 patch. Updates must be in place by June 30, 2017 to avoid any service disruptions. The patch is available on the Community Edition Download Page (https://magento.com/tech-resources/download) and more information is available from PayPal at https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1916&viewlocale=en_US

Aligent_Paypal_Model_Ipn::_postbackAction is affected by this!

**Comment by jonpday** [comment]
thx Achim, we'll be working on this today

**Comment by arosenhagen** [comment]
seems fixed by 26734b721abc315cf8c2f96d583caf67d311e0b9
